import type { Region } from "../../types/domain";

export const regions: Region[] = [
  {
    id: "apple-forest",
    emoji: "🍎",
    unlocked: true,
    characterId: "apple-king",
    mapPosition: { x: 23, y: 20 },
    haileyMarkerPosition: { x: 30, y: 32 },
    theme: {
      pinBorder: "border-fruit-apple",
      heroBg: "bg-region-apple",
      artBg: "bg-region-art-apple",
    },
  },
  {
    id: "strawberry-castle",
    emoji: "🍓",
    unlocked: true,
    characterId: "strawberry-princess",
    mapPosition: { x: 61, y: 18 },
    haileyMarkerPosition: { x: 54, y: 28 },
    theme: {
      pinBorder: "border-fruit-strawberry",
      heroBg: "bg-region-strawberry",
      artBg: "bg-region-art-strawberry",
    },
  },
  {
    id: "banana-beach",
    emoji: "🍌",
    unlocked: true,
    characterId: "banana-sheriff",
    mapPosition: { x: 13, y: 52 },
    haileyMarkerPosition: { x: 22, y: 58 },
    theme: {
      pinBorder: "border-fruit-banana",
      heroBg: "bg-region-banana",
      artBg: "bg-region-art-banana",
    },
  },
  {
    id: "watermelon-lake",
    emoji: "🍉",
    unlocked: true,
    characterId: "watermelon-giant",
    mapPosition: { x: 43, y: 43 },
    haileyMarkerPosition: { x: 48, y: 53 },
    theme: {
      pinBorder: "border-fruit-teal",
      heroBg: "bg-region-watermelon",
      artBg: "bg-region-art-watermelon",
    },
  },
  {
    id: "grape-valley",
    emoji: "🍇",
    unlocked: true,
    characterId: "grape-wizard",
    mapPosition: { x: 80, y: 29 },
    haileyMarkerPosition: { x: 72, y: 38 },
    theme: {
      pinBorder: "border-fruit-grape",
      heroBg: "bg-region-grape",
      artBg: "bg-region-art-grape",
    },
  },
  {
    id: "kiwi-rainforest",
    emoji: "🥝",
    unlocked: false,
    characterId: "kiwi-professor",
    mapPosition: { x: 31, y: 73 },
    haileyMarkerPosition: { x: 38, y: 64 },
    theme: {
      pinBorder: "border-fruit-kiwi",
      heroBg: "bg-region-kiwi",
      artBg: "bg-region-art-kiwi",
    },
  },
  {
    id: "orange-volcano",
    emoji: "🍊",
    unlocked: false,
    characterId: "orange-volcano-keeper",
    mapPosition: { x: 66, y: 69 },
    haileyMarkerPosition: { x: 59, y: 61 },
    theme: {
      pinBorder: "border-fruit-orange",
      heroBg: "bg-region-orange",
      artBg: "bg-region-art-orange",
    },
  },
  {
    id: "coconut-island",
    emoji: "🥥",
    unlocked: false,
    characterId: "coconut-captain",
    mapPosition: { x: 90, y: 76 },
    haileyMarkerPosition: { x: 82, y: 68 },
    theme: {
      pinBorder: "border-fruit-coconut",
      heroBg: "bg-region-coconut",
      artBg: "bg-region-art-coconut",
    },
  },
];
